{
    "rm" = "rm -i";
    "rmrf" = "rm -rf";
    "ls" = "ls -G";
    "l" = "ls -lah";
    "lt" = "ls -lth";
    "ltr" = "ls -lthr";
    "ta" = "tmux attach -t";
    "tls" = "tmux ls";
    "tn" = "tmux new -s";
    "tkill" = "tmux kill-session -t";
    "t2w" = "tmux new-window \\; splitw -h \\;";
    "t2ws" = "t2w \\; setw sync";
    "t4w" = "tmux new-window \\; splitw -h \\; splitw -v \\; select-pane -t 0 \\; splitw -v";
    "t4ws" = "t4w \\; setw sync";
    "t6w" = "tmux new-window \\; splitw -h \\; splitw -v -p 66 \\; splitw -v \\; select-pane -t 0 \\; splitw -v -p 66 \\; splitw -v";
    "t6ws" = "t6w \\; setw sync";
    "ns" = "sudo netstat -taupenl";
    "nsls" = "ns|grep LISTEN";
    "mtr" = "mtr -t";
    "mtra4" = "mtr -bzwe4";
    "mtra6" = "mtr -bzwe6";
    "digna" = "dig +noall +answer";
    "dignar" = "dig -x";
    "connect" = "openssl s_client -showcerts -connect";
    "httpc" = "http --follow --all --headers";
    "syslog" = "sudo tail -f /var/log/syslog";
    "iptlog" = "sudo tail -f /var/log/iptables.log";
    "seculog" = "sudo less /var/log/securityUpgrades.log";
    "sshi" = "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null";
    "sship" = "sshi -o PreferredAuthentications=password -o PubkeyAuthentication=no";
    "scpi" = "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null";
    "scpip" = "scpi -o PreferredAuthentications=password -o PubkeyAuthentication=no";
    "python" = "python3";
    "venv" = "python -m venv venv";
    "vact" = "source venv/bin/activate";
    "sus" = "sudo -s";
    "dd" = "sudo dd status=progress";
    "c" = "clear";
    "dwc" = ''darwin-rebuild check --flake ".#aarch64"'';
    "dwb" = ''darwin-rebuild switch --flake ".#aarch64"'';
    "ks" = "tmux kill-server";
    "ga" = "git add";
    "gc" = "git commit";
    "gco" = "git checkout";
    "gcp" = "git cherry-pick";
    "gdiff" = "git diff";
    "gl" = "git prettylog";
    "gp" = "git push";
    "gs" = "git status";
    "gt" = "git tag";
    "myip" = "curl -s ifconfig.co";
    "k" = "kubectl";
    "tail" = "tail -n 40";
    "tf" = "terraform";
}
